### ISSUE TITLE
Slow turns

### ISSUE THREAD

**Issue by HeChengHui** [nilseuropa/vector_description#3]
Thank you for the proto file.

I have been playing with it in Webots and realised that whenever I try to turn by setting the velocity on one side to some negative value and the other side some positive value, the turn doesn't happen immediately. 

I thought it might be due to some inertia or mass in the physics that caused it to not turn properly, but removing them doesn't remedy this problem.

I can zip you the edited PROTO file if you want.

**Comment by nilseuropa** [comment]
Dear HeChengHui,

I am not using WeBots, so I am not sure if I can help you with this. Sorry

**Comment by HeChengHui** [comment]
@nilseuropa 
sure no problem. Just raising this potential issue.
